/** Blog list */
export const FETCH_BLOG_LIST = "FETCH_BLOG_LIST";
export const FETCH_BLOG_LIST_SUCCESS = "FETCH_BLOG_LIST_SUCCESS";
export const FETCH_BLOG_LIST_ERROR = "FETCH_BLOG_LIST_ERROR";

/** Blog Categories list */
export const FETCH_BLOG_CATEGORIES_LIST = "FETCH_BLOG_CATEGORIES_LIST";
export const FETCH_BLOG_CATEGORIES_LIST_SUCCESS =
  "FETCH_BLOG_CATEGORIES_LIST_SUCCESS";
export const FETCH_BLOG_CATEGORIES_LIST_ERROR =
  "FETCH_BLOG_CATEGORIES_LIST_ERROR";

/** Blog featured Products list */
export const FETCH_BLOG_FEATURED_PRODUCT_LIST =
  "FETCH_BLOG_FEATURED_PRODUCT_LIST";
export const FETCH_BLOG_FEATURED_PRODUCT_LIST_SUCCESS =
  "FETCH_BLOG_FEATURED_PRODUCT_LIST_SUCCESS";
export const FETCH_BLOG_FEATURED_PRODUCT_LIST_ERROR =
  "FETCH_BLOG_FEATURED_PRODUCT_LIST_ERROR";

/** Blog Archive list */
export const FETCH_BLOG_ARCHIVE_LIST = "FETCH_BLOG_ARCHIVE_LIST";
export const FETCH_BLOG_ARCHIVE_LIST_SUCCESS =
  "FETCH_BLOG_ARCHIVE_LIST_SUCCESS";
export const FETCH_BLOG_ARCHIVE_LIST_ERROR = "FETCH_BLOG_ARCHIVE_LIST_ERROR";

/** Blog Tags list */
export const FETCH_BLOG_TAGS_LIST = "FETCH_BLOG_TAGS_LIST";
export const FETCH_BLOG_TAGS_LIST_SUCCESS = "FETCH_BLOG_TAGS_LIST_SUCCESS";
export const FETCH_BLOG_TAGS_LIST_ERROR = "FETCH_BLOG_TAGS_LIST_ERROR";
