/** Shop Product list */
export const FETCH_SHOP_PRODUCT_LIST = "FETCH_SHOP_PRODUCT_LIST";
export const FETCH_SHOP_PRODUCT_LIST_SUCCESS =
  "FETCH_SHOP_PRODUCT_LIST_SUCCESS";
export const FETCH_SHOP_PRODUCT_LIST_ERROR = "FETCH_SHOP_PRODUCT_LIST_ERROR";

