/**Featured Cart Product list */
export const FETCH_SHOPPING_CART_PRODUCT_LIST = "FETCH_SHOPPING_CART_PRODUCT_LIST"
export const FETCH_SHOPPING_CART_PRODUCT_LIST_SUCCESS = "FETCH_SHOPPING_CART_PRODUCT_LIST_SUCCESS"
export const FETCH_SHOPPING_CART_PRODUCT_LIST_ERROR = "FETCH_SHOPPING_CART_PRODUCT_LIST_ERROR"

/**Featured Cart RemoveProduct */
export const FETCH_CART_REMOVE_PRODUCT = "FETCH_CART_REMOVE_PRODUCT"
export const FETCH_CART_REMOVE_PRODUCT_SUCCESS = "FETCH_CART_REMOVE_PRODUCT_SUCCESS"
export const FETCH_CART_REMOVE_PRODUCT_ERROR = "FETCH_CART_REMOVE_PRODUCT_ERROR"

