/** Home Product Types list */
export const FETCH_PRODUCT_TYPE_LIST = "FETCH_PRODUCT_TYPE_LIST"
export const FETCH_PRODUCT_TYPE_LIST_SUCCESS = "FETCH_PRODUCT_TYPE_LIST_SUCCESS"
export const FETCH_PRODUCT_TYPE_LIST_ERROR = "FETCH_PRODUCT_TYPE_LIST_ERROR"
